(add-to-list 'load-path "~/.emacs.d/vendor")

(setq custom-file "~/.emacs.d/bjenkinz/custom.el")
(load custom-file 'noerror)

(load "bjenkinz/theme")
(load "bjenkinz/env")
(load "bjenkinz/global")
(load "bjenkinz/defuns")
(load "bjenkinz/bindings")
(load "bjenkinz/fonts")
(load "bjenkinz/utf-8")
(load "bjenkinz/scratch")
(load "bjenkinz/diff")
(load "bjenkinz/ido")
(load "bjenkinz/org")
(load "bjenkinz/javascript")
(load "bjenkinz/ri-emacs")
(load "bjenkinz/mac")
(load "bjenkinz/server-mode")
(load "bjenkinz/shell-mode")

;; Private stuff goes here (TODO)
;; (load "bjenkinz/private" 'noerror)

(vendor 'ruby-mode)
;; (vendor 'rinari)
(vendor 'maxframe      'mf 'maximize-frame)
;; (vendor 'coffee-mode)
;; (vendor 'haml-mode)
(vendor 'magit         'magit-status)
(vendor 'psvn          'svn-status)
(vendor 'js2-mode      'js2-mode)
(vendor 'markdown-mode 'markdown-mode)
(vendor 'inf-ruby      'inf-ruby)
(vendor 'rcodetools    'xmp)
(vendor 'mode-line-bell)
