(add-to-list 'load-path "~/.emacs.d/vendor")

(load "bjenkinz/theme")
(load "bjenkinz/env")
(load "bjenkinz/global")
(load "bjenkinz/defuns")
(load "bjenkinz/bindings")
(load "bjenkinz/tabs")
(load "bjenkinz/fonts")
(load "bjenkinz/utf-8")
(load "bjenkinz/scratch")
(load "bjenkinz/diff")
(load "bjenkinz/ido")
(load "bjenkinz/javascript")
(load "bjenkinz/mac")
(load "bjenkinz/server-mode")
(load "bjenkinz/shell-mode")
(load "bjenkinz/scala")

(vendor 'ruby-mode)
(vendor 'maxframe      'mf 'maximize-frame)
(vendor 'magit         'magit-status)
(vendor 'js2-mode      'js2-mode)
(vendor 'markdown-mode 'markdown-mode)
(vendor 'inf-ruby      'inf-ruby)
(vendor 'rcodetools    'xmp)
(vendor 'yasnippet)
(vendor 'mode-line-bell)
